# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7c18eb5935cc1413d2c566ce475096b2b6691c53c705ef2375d0a0c75ac91ad2e0046c0e9d62602a3d04e30b482cbc6620d70a1d74a687fe1d9ea7b2fa8a118

test:
  secret_key_base: 83eaf3ce84112a12a7359640c0c77a643bcc1cb8aab030ea3d0e32befb9265012eccda8c9578d482d465c4e472332eda8c13cb776bd818515c503e1fef86e898

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
